apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Deployment.yml
- DeploymentBroadcaster.yml
- DeploymentTodos.yml
- IngressService.yml
- NodePortService.yml
- NodePortTodoService.yml
- ConfigMap.yml
- ConfigMapTodo.yml
- CronJob.yml