apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: project-server-staging
  labels:
    environment: staging

namespace: staging
resources:
- ../../base

patches:
- path: patches/broadcaster-log-only.yaml