apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  labels:
    environment: staging
  name: project-server-staging

namespace: staging
resources:
- ../../base

patches:
- path: patches/broadcaster-log-only.yaml
images:
- name: PROJECT/IMAGE_BACKUP
  newName: europe-west1-docker.pkg.dev/our-reason-470418-t4/my-repository/zelhs/backup-service
  newTag: main-d99ec6e50e70a0a3ec02d45380e8fc21f9cbadcc
- name: PROJECT/IMAGE_BROADCASTER
  newName: europe-west1-docker.pkg.dev/our-reason-470418-t4/my-repository/zelhs/broadcaster
  newTag: main-d99ec6e50e70a0a3ec02d45380e8fc21f9cbadcc
- name: PROJECT/IMAGE_RANDOM
  newName: europe-west1-docker.pkg.dev/our-reason-470418-t4/my-repository/zelhs/random-article
  newTag: main-d99ec6e50e70a0a3ec02d45380e8fc21f9cbadcc
- name: PROJECT/IMAGE_SERVER
  newName: europe-west1-docker.pkg.dev/our-reason-470418-t4/my-repository/zelhs/project_server
  newTag: main-d99ec6e50e70a0a3ec02d45380e8fc21f9cbadcc
- name: PROJECT/IMAGE_TODO
  newName: europe-west1-docker.pkg.dev/our-reason-470418-t4/my-repository/zelhs/todoapp
  newTag: main-d99ec6e50e70a0a3ec02d45380e8fc21f9cbadcc
